name: 游닄 Ofrecer Libro
description: Ofrecer un libro para a침adir a la biblioteca
title: "游닄 Ofrecer: "
labels: ["ofrecer-libro"]
body:
  - type: markdown
    attributes:
      value: |
        ## Ofrecer un Libro
        춰Gracias por contribuir a la biblioteca! Completa este formulario para ofrecer un libro.
  
  - type: input
    id: titulo
    attributes:
      label: 游닀 T칤tulo del libro
      description: Nombre completo del libro
      placeholder: "Ej: Cien a침os de soledad"
    validations:
      required: true
  
  - type: input
    id: autor
    attributes:
      label: 九꽲잺 Autor/a
      description: Nombre del autor (opcional)
      placeholder: "Ej: Gabriel Garc칤a M치rquez"
    validations:
      required: false
  
  - type: input
    id: donante
    attributes:
      label: 游녻 Tu nombre
      description: Tu nombre completo
      placeholder: "Ej: Mar칤a Garc칤a"
    validations:
      required: true
  
  - type: textarea
    id: comentarios
    attributes:
      label: 游눫 Comentarios adicionales
      description: Informaci칩n sobre el estado del libro, d칩nde est치 ubicado, etc. (opcional)
      placeholder: "Ej: Libro en buen estado, est치 en mi escritorio"
    validations:
      required: false
